# Synthetic Datasets

python runner.py --model gothic --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 91 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 6 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 6 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic
python runner.py --model insdpc --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 6 --data_root datasets --out_dir outputs/insdpc/synthetic
python runner.py --model amd_dbscan --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/synthetic
python runner.py --model mdbscan --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/synthetic
python runner.py --model spectral --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 6 --data_root datasets --out_dir outputs/spectral/synthetic
python runner.py --model gnn --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 6 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/synthetic
python runner.py --model idec --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 6 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/synthetic
python runner.py --model gnn_contrastive --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 6 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/synthetic

python runner.py --model gothic --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 120 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 7 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 7 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic
python runner.py --model insdpc --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 7 --data_root datasets --out_dir outputs/insdpc/synthetic
python runner.py --model amd_dbscan --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/synthetic
python runner.py --model mdbscan --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/synthetic
python runner.py --model spectral --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 7 --data_root datasets --out_dir outputs/spectral/synthetic
python runner.py --model gnn --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 7 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/synthetic
python runner.py --model idec --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 7 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/synthetic
python runner.py --model gnn_contrastive --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 7 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/synthetic

python runner.py --model gothic --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 85 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 31 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 31 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic
python runner.py --model insdpc --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 31 --data_root datasets --out_dir outputs/insdpc/synthetic
python runner.py --model amd_dbscan --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/synthetic
python runner.py --model mdbscan --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/synthetic
python runner.py --model spectral --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 31 --data_root datasets --out_dir outputs/spectral/synthetic
python runner.py --model gnn --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 31 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/synthetic
python runner.py --model idec --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 31 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/synthetic
python runner.py --model gnn_contrastive --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 31 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/synthetic

python runner.py --model gothic --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 25 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 2 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 2 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic
python runner.py --model insdpc --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 2 --data_root datasets --out_dir outputs/insdpc/synthetic
python runner.py --model amd_dbscan --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/synthetic
python runner.py --model mdbscan --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/synthetic
python runner.py --model spectral --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --data_root datasets --out_dir outputs/spectral/synthetic
python runner.py --model gnn --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/synthetic
python runner.py --model idec --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/synthetic
python runner.py --model gnn_contrastive --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/synthetic

python runner.py --model gothic --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 50 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 2 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 2 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic
python runner.py --model insdpc --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 2 --data_root datasets --out_dir outputs/insdpc/synthetic
python runner.py --model amd_dbscan --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/synthetic
python runner.py --model mdbscan --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/synthetic
python runner.py --model spectral --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --data_root datasets --out_dir outputs/spectral/synthetic
python runner.py --model gnn --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/synthetic
python runner.py --model idec --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/synthetic
python runner.py --model gnn_contrastive --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/synthetic

python runner.py --model gothic --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 100 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 2 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 2 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic
python runner.py --model insdpc --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 2 --data_root datasets --out_dir outputs/insdpc/synthetic
python runner.py --model amd_dbscan --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/synthetic
python runner.py --model mdbscan --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/synthetic
python runner.py --model spectral --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --data_root datasets --out_dir outputs/spectral/synthetic
python runner.py --model gnn --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/synthetic
python runner.py --model idec --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/synthetic
python runner.py --model gnn_contrastive --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/synthetic

python runner.py --model gothic --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 80 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.15 --b_boundary 20 --d_model 64 --n_heads 4 --attn_hidden 64 --n_transformer_layers 3 --train_epochs 2000 --lr 0.002 --weight_decay 0.000001 --k_target 3 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 3 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic
python runner.py --model insdpc --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 3 --data_root datasets --out_dir outputs/insdpc/synthetic
python runner.py --model amd_dbscan --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/synthetic
python runner.py --model mdbscan --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/synthetic
python runner.py --model spectral --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --data_root datasets --out_dir outputs/spectral/synthetic
python runner.py --model gnn --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/synthetic
python runner.py --model idec --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/synthetic
python runner.py --model gnn_contrastive --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/synthetic

python runner.py --model gothic --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 45 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 15 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 15 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic
python runner.py --model insdpc --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 15 --data_root datasets --out_dir outputs/insdpc/synthetic
python runner.py --model amd_dbscan --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/synthetic
python runner.py --model mdbscan --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/synthetic
python runner.py --model spectral --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 15 --data_root datasets --out_dir outputs/spectral/synthetic
python runner.py --model gnn --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 15 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/synthetic
python runner.py --model idec --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 15 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/synthetic
python runner.py --model gnn_contrastive --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 15 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/synthetic

# Real Datasets

python runner.py --model gothic --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 5 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.6 --b_boundary 5 --d_model 128 --n_heads 2 --attn_hidden 64 --n_transformer_layers 3 --train_epochs 2000 --lr 0.003 --weight_decay 0.001 --k_target 3 --data_root datasets --out_dir outputs/gothic/real
python runner.py --model kmeans --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 3 --data_root datasets --out_dir outputs/kmeans/real
python runner.py --model dbscan --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/real
python runner.py --model hdbscan --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/real
python runner.py --model insdpc --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 3 --data_root datasets --out_dir outputs/insdpc/real
python runner.py --model amd_dbscan --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/real
python runner.py --model mdbscan --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/real
python runner.py --model spectral --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --data_root datasets --out_dir outputs/spectral/real
python runner.py --model gnn --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/real
python runner.py --model idec --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/real
python runner.py --model gnn_contrastive --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/real

python runner.py --model gothic --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 70 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 3 --data_root datasets --out_dir outputs/gothic/real
python runner.py --model kmeans --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 3 --data_root datasets --out_dir outputs/kmeans/real
python runner.py --model dbscan --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/real
python runner.py --model hdbscan --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/real
python runner.py --model insdpc --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 3 --data_root datasets --out_dir outputs/insdpc/real
python runner.py --model amd_dbscan --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/real
python runner.py --model mdbscan --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/real
python runner.py --model spectral --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --data_root datasets --out_dir outputs/spectral/real
python runner.py --model gnn --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/real
python runner.py --model idec --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/real
python runner.py --model gnn_contrastive --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 3 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/real

python runner.py --model gothic --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 15 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.9 --b_boundary 5 --d_model 96 --n_heads 8 --attn_hidden 256 --n_transformer_layers 1 --train_epochs 2000 --lr 0.0003 --weight_decay 0.0001 --k_target 2 --data_root datasets --out_dir outputs\gothic\real
python runner.py --model kmeans --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 2 --data_root datasets --out_dir outputs/kmeans/real
python runner.py --model dbscan --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/real
python runner.py --model hdbscan --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/real
python runner.py --model insdpc --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 2 --data_root datasets --out_dir outputs/insdpc/real
python runner.py --model amd_dbscan --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/real
python runner.py --model mdbscan --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/real
python runner.py --model spectral --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --data_root datasets --out_dir outputs/spectral/real
python runner.py --model gnn --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/real
python runner.py --model idec --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/real
python runner.py --model gnn_contrastive --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 2 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/real

python runner.py --model gothic --run_id digits_ID001 --dataset digits --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 120 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.4 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 4 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 10 --data_root datasets --out_dir outputs/gothic/real
python runner.py --model kmeans --run_id digits_ID001 --dataset digits --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 10 --data_root datasets --out_dir outputs/kmeans/real
python runner.py --model dbscan --run_id digits_ID001 --dataset digits --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/real
python runner.py --model hdbscan --run_id digits_ID001 --dataset digits --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/real
python runner.py --model insdpc --run_id digits_ID001 --dataset digits --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 10 --data_root datasets --out_dir outputs/insdpc/real
python runner.py --model amd_dbscan --run_id digits_ID001 --dataset digits --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/real
python runner.py --model mdbscan --run_id digits_ID001 --dataset digits --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/real
python runner.py --model spectral --run_id digits_ID001 --dataset digits --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 10 --data_root datasets --out_dir outputs/spectral/real
python runner.py --model gnn --run_id digits_ID001 --dataset digits --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 10 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/real
python runner.py --model idec --run_id digits_ID001 --dataset digits --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 10 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/real
python runner.py --model gnn_contrastive --run_id digits_ID001 --dataset digits --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 10 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/real

python runner.py --model gothic --run_id olivetti_faces_ID001 --dataset olivetti_faces --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 120 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.4 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 4 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 40 --reduce_dim pca --pca_dim 128 --data_root datasets --out_dir outputs/gothic/real
python runner.py --model kmeans --run_id olivetti_faces_ID001 --dataset olivetti_faces --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 40 --data_root datasets --out_dir outputs/kmeans/real
python runner.py --model dbscan --run_id olivetti_faces_ID001 --dataset olivetti_faces --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/real
python runner.py --model hdbscan --run_id olivetti_faces_ID001 --dataset olivetti_faces --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/real
python runner.py --model insdpc --run_id olivetti_faces_ID001 --dataset olivetti_faces --seed 42 --train_fraction 0.8 --split_strategy balanced --k_neighbors 30 --k_target 40 --data_root datasets --out_dir outputs/insdpc/real
python runner.py --model amd_dbscan --run_id olivetti_faces_ID001 --dataset olivetti_faces --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 1.0 --min_samples 5 --k_scale 15 --data_root datasets --out_dir outputs/amd_dbscan/real
python runner.py --model mdbscan --run_id olivetti_faces_ID001 --dataset olivetti_faces --seed 42 --train_fraction 0.8 --split_strategy balanced --eps_min 0.05 --eps_max 1.0 --n_levels 10 --min_samples 5 --data_root datasets --out_dir outputs/mdbscan/real
python runner.py --model spectral --run_id olivetti_faces_ID001 --dataset olivetti_faces --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 40 --data_root datasets --out_dir outputs/spectral/real
python runner.py --model gnn --run_id olivetti_faces_ID001 --dataset olivetti_faces --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 40 --knn_k 10 --hidden_dim 64 --embed_dim 16 --dropout 0.1 --lr 0.01 --weight_decay 0.0001 --epochs 200 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn/real
python runner.py --model idec --run_id olivetti_faces_ID001 --dataset olivetti_faces --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 40 --latent_dim 16 --hidden_dim 128 --pretrain_epochs 100 --finetune_epochs 200 --lr 0.001 --alpha 1.0 --gamma 1.0 --update_interval 10 --data_root datasets --out_dir outputs/idec/real
python runner.py --model gnn_contrastive --run_id olivetti_faces_ID001 --dataset olivetti_faces --seed 42 --train_fraction 0.8 --split_strategy balanced --k_target 40 --knn_k 10 --hidden_dim 128 --embed_dim 64 --dropout 0.1 --epochs 300 --lr 0.001 --weight_decay 0.0001 --temperature 0.2 --edge_drop 0.2 --feat_drop 0.2 --kmeans_n_init 50 --kmeans_max_iter 500 --data_root datasets --out_dir outputs/gnn_contrastive/real