# Synthetic Datasets

python runner.py --model gothic --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 91 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 6 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 6 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id compound_ID001 --dataset compound --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic

python runner.py --model gothic --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 120 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 7 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 7 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id aggregation_ID001 --dataset aggregation --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic

python runner.py --model gothic --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 93 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 31 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 31 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id d31_ID001 --dataset d31 --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic

python runner.py --model gothic --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 25 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 2 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 2 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id flame_ID001 --dataset flame --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic

python runner.py --model gothic --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 50 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 2 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 2 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id jain_ID001 --dataset jain --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic

python runner.py --model gothic --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 100 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 2 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 2 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id noisy_circles_ID001 --dataset noisy_circles --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic

python runner.py --model gothic --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 60 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 3 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 3 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id pathbased_ID001 --dataset pathbased --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic

python runner.py --model gothic --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 45 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 15 --data_root datasets --out_dir outputs/gothic/synthetic
python runner.py --model kmeans --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 15 --data_root datasets --out_dir outputs/kmeans/synthetic
python runner.py --model dbscan --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/synthetic
python runner.py --model hdbscan --run_id r15_ID001 --dataset r15 --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/synthetic

# Real Datasets

python runner.py --model gothic --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 3 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.5 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 4 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 3 --data_root datasets --out_dir outputs/gothic/real
python runner.py --model kmeans --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 3 --data_root datasets --out_dir outputs/kmeans/real
python runner.py --model dbscan --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/real
python runner.py --model hdbscan --run_id wine_ID001 --dataset wine --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/real

python runner.py --model gothic --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 70 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.3 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 2 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 3 --data_root datasets --out_dir outputs/gothic/real
python runner.py --model kmeans --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 3 --data_root datasets --out_dir outputs/kmeans/real
python runner.py --model dbscan --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/real
python runner.py --model hdbscan --run_id iris_ID001 --dataset iris --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/real

python runner.py --model gothic --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --n_micro 25 --kmeans_n_init 50 --kmeans_max_iter 500 --dist_quantile 0.7 --b_boundary 5 --d_model 32 --n_heads 4 --attn_hidden 64 --n_transformer_layers 8 --train_epochs 2000 --lr 0.001 --weight_decay 0.0001 --k_target 2 --data_root datasets --out_dir outputs/gothic/real
python runner.py --model kmeans --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --kmeans_n_init 50 --kmeans_max_iter 500 --k_target 2 --data_root datasets --out_dir outputs/kmeans/real
python runner.py --model dbscan --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --eps 0.2 --min_samples 5 --data_root datasets --out_dir outputs/dbscan/real
python runner.py --model hdbscan --run_id breast_cancer_ID001 --dataset breast_cancer --seed 42 --train_fraction 0.8 --split_strategy balanced --min_cluster_size 5 --min_samples 5 --cluster_selection_epsilon 0.0 --cluster_selection_method eom --data_root datasets --out_dir outputs/hdbscan/real
